name: github build on test flow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./out
          name: build-artifact
  deploy:
    # Add a dependency to the build job
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          folder: .
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: build-artifact